language: rust

rust:
 - 1.39.0
 - stable
 - beta
 - nightly

script:
  - cargo build
  - cargo test

jobs:
  include:
    - name: minimal versions check
      rust: nightly
      script: rm Cargo.lock && cargo build -Z minimal-versions