[package]
name = "serial_test_test"
description = "External testing crate for serial_test"
license = "MIT"
version = "0.5.0"
authors = ["Tom Parker-Shemilt <palfrey@tevp.net>"]
edition = "2018"

[dev-dependencies]
serial_test = { path="../serial_test" }
lazy_static = "^1.2"
env_logger = "^0.8"
tokio = { version = "0.3", features = ["macros", "rt-multi-thread"] }
tokio-macros = { version = "0.3"}