[package]
name = "serial_test_test"
description = "External testing crate for serial_test"
license = "MIT"
version = "0.9.0"
authors = ["Tom Parker-Shemilt <palfrey@tevp.net>"]
edition = "2018"

[dependencies]
serial_test = { path="../serial_test", default_features = false }
lazy_static = "^1.2"
env_logger = "^0.9"
parking_lot = "^0.12"
wasm-bindgen-test = {version="0.3.0", optional=true}

[dev-dependencies]
tokio = { version = "^1.17", features = ["macros", "rt"] }
actix-rt = { version = "^2.7", features = ["macros"] }
futures-util = {version = "^0.3", default_features = false }

[features]
default = ["serial_test/logging", "serial_test/async", "wasm-bindgen-test"]
file_locks = ["serial_test/file_locks"]