[package]
name = "serial_test_test"
description = "External testing crate for serial_test_derive"
license = "MIT"
version = "0.2.0"
authors = ["Tom Parker-Shemilt <palfrey@tevp.net>"]
edition = "2018"

[dev-dependencies]
serial_test = { path="../serial_test" }
lazy_static = "1.2"
