[package]
name = "serial_test"
description = "Helper crate for serial_test_derive"
license = "MIT"
version = "0.1.0"
authors = ["Tom Parker-Shemilt <palfrey@tevp.net>"]
edition = "2018"
repository = "https://github.com/palfrey/serial_test/"

[dependencies]
lazy_static = "1.2"