[package]
name = "serial_test"
description = "Helper crate for serial_test_derive"
license = "MIT"
version = "0.2.0"
authors = ["Tom Parker-Shemilt <palfrey@tevp.net>"]
edition = "2018"
repository = "https://github.com/palfrey/serial_test/"
readme = "README.md"
categories = ["development-tools::testing"]

[dependencies]
lazy_static = "1.2"
parking_lot = "0.9"