on: 
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0 1 * *'

name: Continuous integration

jobs:
  test:
    name: Test suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.51.0
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v1
      - name: Check formatting
        uses: actions-rs/cargo@v1.0.3
        with:
          command: fmt
          args: -- --check
        if: ${{ matrix.rust == 'nightly' }}
      - name: Clippy
        uses: actions-rs/cargo@v1.0.3
        env:
          RUSTFLAGS: -Dwarnings
        with:
          command: clippy
        continue-on-error: ${{ matrix.rust == 'nightly' || matrix.rust == 'beta' }}
      - run: |
          curl --remote-name https://github.com/ryankurte/cargo-binstall/releases/download/v0.11.1/cargo-binstall-x86_64-unknown-linux-musl.tgz
          tar -zxvf cargo-binstall-x86_64-unknown-linux-musl.tgz
          mv cargo-binstall ~/.cargo/bin
      - name: Install "build all features"
        uses: actions-rs/cargo@v1.0.3
        with:
          command: binstall cargo-all-featutres --no-confirm --version 1.7.0
      - name: Build all features
        uses: actions-rs/cargo@v1.0.3
        with:
          command: build-all-features
      - name: Test all features
        uses: actions-rs/cargo@v1.0.3
        with:
          command: test-all-features          
        env:
          RUST_TEST_THREADS: 3 # So the parallel tests have enough threads
          RUST_LOG: debug

  multi-os-testing:
    name: Test suite
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: Build and test
        uses: actions-rs/cargo@v1.0.3
        with:
          command: test
          args: --all-features -- --nocapture
        env:
          RUST_TEST_THREADS: 3 # So the parallel tests have enough threads
          RUST_LOG: debug

  minimal-versions:
    name: minimal versions check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Remove lock
        run: rm Cargo.lock
      - uses: actions-rs/cargo@v1.0.3
        with:
          command: build
          args: -Z minimal-versions